app/cf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("incoming.urls")),
    path("out/", include("outgoing.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/incoming/urls.py
from django.urls import path

from .views import (
    IncomingCreateView,
    IncomingDetailView,
    IncomingListView,
    IncomingUpdateView,
    search_view,
)

urlpatterns = [
    path("", IncomingListView.as_view(), name="incoming-list"),
    path("detail/<int:pk>/", IncomingDetailView.as_view(), name="incoming-detail"),
    path("update/<int:pk>/", IncomingUpdateView.as_view(), name="incoming-update"),
    path("add-new/", IncomingCreateView.as_view(), name="incoming-create"),
    path("search/", search_view, name="search-view"),
]

app/incoming/models.py
from django.db import models
from django.urls import reverse
from users.models import User


class Incoming(models.Model):
    subject = models.CharField(max_length=255, null=True)
    received = models.DateField(blank=True, null=True)
    dated = models.DateField(blank=True, null=True)
    rfrom = models.CharField(max_length=100, verbose_name="from")
    to = models.CharField(max_length=100, null=True, blank=True)
    cc = models.CharField(max_length=100, null=True, blank=True)
    action = models.CharField(max_length=255, null=True, blank=True)
    forward = models.CharField(max_length=100, null=True, blank=True)
    notes = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to="incoming/files/", blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="incoming_created_by",
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="incoming_updated_by",
    )

    class Meta:
        ordering = ["-received", "subject"]

    def get_absolute_url(self):
        return reverse("incoming-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"({self.pk}) {self.subject}"

app/users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class User(AbstractUser):
    is_clerk = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)

    def get_user_roles(self):
        roles = []
        if self.is_manager:
            roles.append("is_manager")
        if self.is_clerk:
            roles.append("is_clerk")

        return roles if roles else ["user"]

    def __str__(self):
        return self.username


class Profile(models.Model):
    GENDER_LIST = [
        ("F", "Female"),
        ("M", "Male"),
    ]
    photo = models.FileField(upload_to="profile_photos/", blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, blank=True)
    post = models.CharField(max_length=255, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_LIST)
    phone = models.CharField(max_length=25, null=True, default="+1")

    # def get_absolute_url(self):
    #     return reverse("user-profile-detail", kwargs={"slug": self.slug})
    
    def get_absolute_url(self):
        return reverse("profile-update", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            # Newly created object, so set slug
            self.slug = slugify(self.uid)
        super(Profile, self).save(*args, **kwargs)

    def get_profile_initials(self):
        if self.first_name and self.last_name:
            return f"{self.first_name[0]}{self.last_name[0]}"
        return self.user.email[0].upper()

    def __str__(self) -> str:
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return f"{self.user}"

app/incoming/forms.py
from django import forms

from .models import Incoming


class IncomingForm(forms.ModelForm):

    class Meta:
        model = Incoming
        fields = (
            "file",
            "subject",
            "received",
            "dated",
            "rfrom",
            "to",
            "cc",
            "action",
            "forward",
            "notes",
        )
        widgets = {
            "received": forms.DateInput(attrs={"type": "date"}),
            "dated": forms.DateInput(attrs={"type": "date"}),
            "notes": forms.Textarea(attrs={"rows": 2}),
        }

app/incoming/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from outgoing.models import Outgoing

from .forms import IncomingForm
from .models import Incoming


def search_view(request):
    query = request.GET.get("q")
    if query:
        outgoings = Outgoing.objects.filter(
            Q(subject__icontains=query)
            | Q(out_from__icontains=query)
            | Q(to__icontains=query)
            | Q(cc__icontains=query)
            | Q(notes__icontains=query)
            # Assuming action has a name field you want to search
        ).distinct()
        incomings = Incoming.objects.filter(
            Q(subject__icontains=query)
            | Q(rfrom__icontains=query)
            | Q(to__icontains=query)
            | Q(cc__icontains=query)
            | Q(notes__icontains=query)
            | Q(action__icontains=query)
            # Assuming action has a name field you want to search
        ).distinct()
    context = {"query": query, "incomings": incomings, "outgoings": outgoings}
    return render(request, "search_view.html", context)


class IncomingUpdateView(UpdateView):
    model = Incoming
    form_class = IncomingForm


class IncomingCreateView(CreateView):
    model = Incoming
    form_class = IncomingForm


class IncomingDetailView(DetailView):
    model = Incoming


class IncomingListView(ListView):
    model = Incoming
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data_count"] = Incoming.objects.count()
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Incoming.objects.filter(
                Q(subject__icontains=query)
                | Q(rfrom__icontains=query)
                | Q(to__icontains=query)
                | Q(cc__icontains=query)
                | Q(notes__icontains=query)
                | Q(action__icontains=query)
                # Assuming action has a name field you want to search
            ).distinct()
        return super().get_queryset()

app/templates/incoming/incoming_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="px-5">
    <div class="bg-secondary bg-opacity-10 py-3 px-4 shadow rounded-4">
        <h3>{{ incoming.subject|upper }}</h3>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <p><strong>Received:</strong> {{ incoming.received }}</p>
                <p><strong>Dated:</strong> {{ incoming.dated }}</p>
                <p><strong>From:</strong> {{ incoming.rfrom }}</p>
                <p><strong>To:</strong> {{ incoming.to }}</p>
                <p><strong>CC:</strong> {{ incoming.cc }}</p>
                <p><strong>Action:</strong> {{ incoming.action|title }}</p>
            </div>
            <div class="col-md-6">
                <p><strong>Forward:</strong> {{ incoming.forward }}</p>
                <p><strong>Created By:</strong> {{ incoming.created_by }}
                </p>
                <p><strong>Notes:</strong> {{ incoming.notes }}</p>

            </div>
        </div>

        <hr>
        {% if incoming.file %}
        <p><strong>File:</strong> <a target="_new"
                href="{{ incoming.file.url }}">{{ incoming.file.name }}</a>
        </p>
        {% endif %}

        <div class="text-end me-4 mb-4">
            <a class="btn btn-dark me-3"
                href="{% url 'incoming-update' incoming.pk %}">Edit</a>
            <a class="btn btn-outline-dark"
                href="">Delete</a>
        </div>

        <p class="small text-muted text-end"
            title="created">{{ incoming.created_at }}
        </p>
    </div>
</div>
{% endblock %}

app/templates/incoming/incoming_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>{% if form.instance.pk %}
        Update Incoming {{ form.instance.pk }}
        {% else %}
        Create Incoming
        {% endif %}
    </h1>
    <hr>
    <form class="col-lg-4 mx-auto"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="text-end">
            <button type="submit"
                class="btn btn-dark">Save</button>
        </div>
    </form>
</div>
<script>
    $("#id_user").select2();
</script>
{% endblock %}

app/templates/incoming/incoming_list.html
{% extends "base.html" %}

{% load humanize %} 


{% block content %}

<form class="col-lg-4 mx-auto"
    method="get">
    <input class="form-control rounded-4"
        type="text"
        name="q"
        placeholder="Search incoming..."
        value="{{ request.GET.q }}">
    <br>
    <div class="text-end">
        <button class="btn btn-dark px-5 rounded-4"
            type="submit">Search</button>
    </div>
</form>
<a class="btn btn-dark"
    href="{% url 'incoming-create' %}">Add new</a>
<div class="fw-bold fs-5 float-end">
    {{data_count|intcomma}}
</div>
<hr>
<div class="table responseive">
    <table class="table table-sm table-hover small">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject</th>
                <th scope="col">From</th>
                <th scope="col">Received</th>
                <th scope="col">Dated</th>
                <th scope="col">Created</th>
            </tr>
        </thead>
        <tbody>
            {% for incoming in object_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><a class="text-dark" href="{{incoming.get_absolute_url}}">
                        {{ incoming.subject|upper|truncatechars:70 }}</a></td>
                <td>{{ incoming.rfrom|upper }}</td>
                <td>{{ incoming.received|default_if_none:'-' }}</td>
                <td>{{ incoming.dated|default_if_none:'-' }}</td>
                <td>{{ incoming.date|default_if_none:'-' }}</td>
            </tr>
            {% empty %}
            <li>No incoming correspondences found.</li>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if page_obj %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}


{% endblock content %}